services:
  - type: web
    name: dental-clinic
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dentalclinic.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dental-clinic-db
          property: connectionString

databases:
  - name: dental-clinic-db
